puts "🌱 Seeding Initiated 🌱 "


puts "Seeding users..."
User.create(username: "Grant123", email: "grant123@gmail.com", address: "123 Grant Street, Granton, GR USA", name: "Grant Pierce", phone: "1231231231", password: "123Grant")
User.create(username: "test", email: "test@gmail.com", address: "123 Test Street, Testford, TE USA", name: "Test", phone: "0000000000", password: "test")
User.create(username: "Sofia13", email: "sofversoza@gmail.com", address: "666 Elm Street, 85254", name: "Sofia Versoza", phone: "6027846254", password: "sofia123")
User.create(username: "Brooks88", email: "brooks12345@gmail.com", address: "5656 Springs Colorado", name: "Brooks", phone: "7327183638", password: "brooks123")
User.create(username: "Gibson", email: "mgibson@gmail.com", address: "434 W 154th St", name: "Test", phone: "564783920", password: "password")


puts "Seeding books..."
Book.create(title: "The Fellowship of the Ring", 
            author: "J.R.R. Tolkien", 
            genre: "Fantasy", 
            category: "Fiction", 
            description: "One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkeness bind them...\n\nIn ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, The Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others. But the One Ring was taken from him, and though he sought it throughout Middle-earth, it remained lost to him. After many ages it fell into the hands of Bilbo Baggins, as told in The Hobbit.\n\nIn a sleepy village in the Shire, young Frodo Baggins finds himself faced with an immense task, as his elderly cousin Bilbo entrusts the Ring to his care. Frodo must leave his home and make a perilous journey across Middle-earth to the Cracks of Doom, there to destroy the Ring and foil the Dark Lord in his evil purpose.", 
            rating: 4.37,
            price: 3.57,
            image: "https://m.media-amazon.com/images/I/41kUPvqlguL.jpg",
            total_quantity: 250,
            quantity_in_stock: 42,
            date_added: DateTime.new(2022, 1, 26, 1, 5, 12),
            discount: 0)

Book.create(title: "The Two Towers", 
            author: "J.R.R. Tolkien", 
            genre: "Fantasy", 
            category: "Fiction", 
            description: "One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them...\n\nFrodo and his Companions of the Ring have been beset by danger during their quest to prevent the Ruling Ring from falling into the hands of the Dark Lord by destroying it in the Cracks of Doom. They have lost the wizard, Gandalf, in a battle in the Mines of Moria. And Boromir, seduced by the power of the Ring, tried to seize it by force. While Frodo and Sam made their escape, the rest of the company was attacked by Orcs. Now they continue the journey alone down the great River Anduin—alone, that is, save for the mysterious creeping figure that follows wherever they go.", 
            rating: 4.46,
            price: 3.57,
            image: "https://m.media-amazon.com/images/I/4123zOAwAgL.jpg",
            total_quantity: 250,
            quantity_in_stock: 142,
            date_added: DateTime.new(2022, 1, 26, 1, 6, 46),
            discount: 0)

Book.create(title: "The Return of the King", 
            author: "J.R.R. Tolkien", 
            genre: "Fantasy", 
            category: "Fiction", 
            description: "One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkeness bind them...\n\nIn the third volume of The Lord of the Rings trilogy the good and evil forces join battle, and we see that the triumph of good is not absolute. The Third Age of Middle-earth ends, and the age of the dominion of Men begins.", 
            rating: 4.87,
            price: 3.57,
            image: "https://m.media-amazon.com/images/I/41KGl2FqeAL.jpg",
            total_quantity: 250,
            quantity_in_stock: 81,
            date_added: DateTime.new(2022, 1, 26, 1, 6, 58),
            discount: 0)

Book.create(title: "The Hobbit, or There and Back Again", 
            author: "J.R.R. Tolkien", 
            genre: "Fantasy", 
            category: "Fiction", 
            description: "In a hole in the ground there lived a hobbit. Not a nasty, dirty, wet hole, filled with the ends of worms and an oozy smell, nor yet a dry, bare, sandy hole with nothing in it to sit down on or to eat: it was a hobbit-hole, and that means comfort.\n\nWritten for J.R.R. Tolkien’s own children, The Hobbit met with instant critical acclaim when it was first published in 1937. Now recognized as a timeless classic, this introduction to the hobbit Bilbo Baggins, the wizard Gandalf, Gollum, and the spectacular world of Middle-earth recounts of the adventures of a reluctant hero, a powerful and dangerous ring, and the cruel dragon Smaug the Magnificent.", 
            rating: 4.28,
            price: 3.57,
            image: "https://images-na.ssl-images-amazon.com/images/I/710+HcoP38L.jpg",
            total_quantity: 100,
            quantity_in_stock: 60,
            date_added: DateTime.new(2022, 1, 26, 1, 7, 5),
            discount: 25)

Book.create(title: "Goodnight Moon", 
            author: "Margaret Wise Brown", 
            genre: "Childrens", 
            category: "Fiction", 
            description: "In a great green room, tucked away in bed, is a little bunny. 'Goodnight room, goodnight moon.' And to all the familiar things in the softly lit room -- to the picture of the three little bears sitting on chairs, to the clocks and his socks, to the mittens and the kittens, to everything one by one -- the little bunny says goodnight.\n\nIn this classic of children's literature, beloved by generations of readers and listeners, the quiet poetry of the words and the gentle, lulling illustrations combine to make a perfect book for the end of the day.", 
            rating: 4.29,
            price: 10.13,
            image: "https://images-na.ssl-images-amazon.com/images/I/91WuHblNkEL.jpg",
            total_quantity: 150,
            quantity_in_stock: 57,
            date_added: DateTime.new(2022, 1, 26, 1, 15, 38),
            discount: 90)

Book.create(title: "Pale Blue Dot: A Vision of the Human Future in Space", 
            author: "Carl Sagan, Ann Druyan", 
            genre: "Science", 
            category: "Nonfiction", 
            description: "Pulitzer Prize-winning author Carl Sagan traces our exploration of space and suggests that our very survival may depend on the wise use of other worlds. This stirring book reveals how scientific discovery has altered our perception of who we are and where we stand, and challenges us to weigh what we will do with that knowledge.", 
            rating: 4.30,
            price: 4.51,
            image: "https://m.media-amazon.com/images/I/51uklIvHaLL.jpg",
            total_quantity: 150,
            quantity_in_stock: 62,
            date_added: DateTime.new(2022, 1, 26, 1, 21, 19),
            discount: 0)

Book.create(title: "Beyond Good & Evil: Prelude to a Philosophy of the Future", 
            author: "Friedrich Nietzsche", 
            genre: "Philosophy", 
            category: "Nonfiction", 
            description: "Beyond Good and Evil confirmed Nietzsche's position as the towering European philosopher of his age. The work dramatically rejects the tradition of Western thought with its notions of truth and God, good and evil. Nietzsche demonstrates that the Christian world is steeped in a false piety and infected with a 'slave morality'. With wit and energy, he turns from this critique to a philosophy that celebrates the present and demands that the individual imposes their own 'will to power' upon the world.", 
            rating: 4.71,
            price: 4.51,
            image: "https://images-na.ssl-images-amazon.com/images/I/41ND61b-wqL._SX322_BO1,204,203,200_.jpg",
            total_quantity: 100,
            quantity_in_stock: 19,
            date_added: DateTime.new(2022, 1, 26, 1, 26, 20),
            discount: 0)

Book.create(title: "For a New Liberty", 
            author: "Murray N. Rothbard", 
            genre: "Philosophy", 
            category: "Nonfiction", 
            description: "A classic that for over two decades has been hailed as the best general work on libertarianism available. Rothbard begins with a quick overview of its historical roots, and then goes on to define libertarianism as resting 'upon one single axiom: that no man or group of men shall aggress upon the person or property of anyone else.' He writes a withering critique of the chief violator of liberty: the State. Rothbard then provides penetrating libertarian solutions for many of today's most pressing problems, including poverty, war, threats to civil liberties, the education crisis, and more.", 
            rating: 4.32,
            price: 4.51,
            image: "https://images-na.ssl-images-amazon.com/images/I/41hHmHFnOGL._SX312_BO1,204,203,200_.jpg",
            total_quantity: 100,
            quantity_in_stock: 73,
            date_added: DateTime.new(2022, 1, 26, 1, 31, 1),
            discount: 0)

Book.create(title: "A Brief History of Time", 
            author: "Stephen Hawking", 
            genre: "Science", 
            category: "Nonfiction", 
            description: "A landmark volume in science writing by one of the great minds of our time, Stephen Hawking’s book explores such profound questions as: How did the universe begin—and what made its start possible? Does time always flow forward? Is the universe unending—or are there boundaries? Are there other dimensions in space? What will happen when it all ends?\n\nTold in language we all can understand, A Brief History of Time plunges into the exotic realms of black holes and quarks, of antimatter and “arrows of time,” of the big bang and a bigger God—where the possibilities are wondrous and unexpected. With exciting images and profound imagination, Stephen Hawking brings us closer to the ultimate secrets at the very heart of creation.", 
            rating: 4.70,
            price: 4.51,
            image: "https://images-na.ssl-images-amazon.com/images/I/A1xkFZX5k-L.jpg",
            total_quantity: 100,
            quantity_in_stock: 80,
            date_added: DateTime.new(2022, 1, 26, 1, 42, 53),
            discount: 20)

Book.create(title: "The Code Book: The Science of Secrecy from Ancient Egypt to Quantum Cryptography", 
            author: "Simon Singh", 
            genre: "Science", 
            category: "Nonfiction", 
            description: "In his first book since the bestselling Fermat’s Enigma, Simon Singh offers the first sweeping history of encryption, tracing its evolution and revealing the dramatic effects codes have had on wars, nations, and individual lives. From Mary, Queen of Scots, trapped by her own code, to the Navajo Code Talkers who helped the Allies win World War II, to the incredible (and incredibly simple) logisitical breakthrough that made Internet commerce secure, The Code Book tells the story of the most powerful intellectual weapon ever known: secrecy.", 
            rating: 4.27,
            price: 4.51,
            image: "https://images-na.ssl-images-amazon.com/images/I/71fSWKBI1CL.jpg",
            total_quantity: 100,
            quantity_in_stock: 35,
            date_added: DateTime.new(2022, 1, 26, 1, 47, 13),
            discount: 0)

Book.create(title: "Coding for dummies", 
            author: "Nikhil Abraham", 
            genre: "Software Engineering", 
            category: "Nonfiction", 
            description: "Learn the basics of five different coding languages. HTML, CSS, JavaScript, Ruby, and python", 
            rating: 4.33,
            price: 9.52,
            image: "https://images-na.ssl-images-amazon.com/images/I/51R-0eSy2FL._SX403_BO1,204,203,200_.jpg",
            total_quantity: 375,
            quantity_in_stock: 112,
            date_added: DateTime.new(2022, 1, 27, 11, 7, 15),
            discount: 0)

Book.create(title: "Warrior in the Garden", 
            author: "Nobuo Yagari", 
            genre: "Philosophy", 
            category: "Nonfiction", 
            description: "WARRIOR IN THE GARDEN is a unique book of the ancient warrior code for modern times. Through famous stories of samurai, samurai education, origins of the arts of Judo and Jiu Jitsu and his own martial arts journey, Nobuo Yagai provides fresh insight into timeless wisdom.This book was inspired by the original book Bushido and Judo founder Jigoro Kano’s philosophy; peace through the warrior mind set.It will inspire today’s warriors to infuse ancient wisdom in modern times.
            WARRRIOR IN THE GARDEN is not just for martial artists. It is for anyone who dares to be a life warrior.", 
            rating: 4.2,
            price: 9.99,
            image: "https://images-na.ssl-images-amazon.com/images/I/71ow56k3ymL.jpg",
            total_quantity: 175,
            quantity_in_stock: 88,
            date_added: DateTime.new(2022, 1, 27, 11, 17, 22),
            discount: 8)

Book.create(title: "The Art of the Long View", 
            author: "Peter Schwartz", 
            genre: "Philosophy", 
            category: "Nonfiction", 
            description: "What increasingly affects all of us, whether professional planners or individuals preparing for a better future, is not the tangibles of life—bottom-line numbers, for instance—but the intangibles: our hopes and fears, our beliefs and dreams. Only stories—scenarios—and our ability to visualize different kinds of futures adequately capture these intangibles. In The Art of the Long View, now for the first time in paperback and with the addition of an all-new User's Guide, Peter Schwartz outlines the 'scenaric' approach, giving you the tools for developing a strategic vision within your business.", 
            rating: 4.10,
            price: 12.99,
            image: "https://m.media-amazon.com/images/P/0385267320.01._SCLZZZZZZZ_SX500_.jpg",
            total_quantity: 120,
            quantity_in_stock: 34,
            date_added: DateTime.new(2022, 1, 27, 11, 26, 3),
            discount: 10)

Book.create(title: "Make Your Bed", 
            author: "William H. McRaven", 
            genre: "Philosophy", 
            category: "Nonfiction", 
            description: "If you want to change the world, start off by making your bed.\n\nOn May 17, 2014, Admiral William H. McRaven addressed the graduating class of the University of Texas at Austin on their Commencement day. Taking inspiration from the university's slogan, 'What starts here changes the world,' he shared the ten principles he learned during Navy Seal training that helped him overcome challenges not only in his training and long Naval career, but also throughout his life; and he explained how anyone can use these basic lessons to change themselves-and the world-for the better.", 
            rating: 4.29,
            price: 12.99,
            image: "https://images-na.ssl-images-amazon.com/images/I/81tqQak257L.jpg",
            total_quantity: 150,
            quantity_in_stock: 23,
            date_added: DateTime.new(2022, 1, 27, 11, 37, 38),
            discount: 15)
            
Book.create(title: "Mastery", 
            author: "Robert Greene", 
            genre: "Philosophy", 
            category: "Nonfiction", 
            description: "What did Charles Darwin, middling schoolboy and underachieving second son, do to become one of the earliest and greatest naturalists the world has known? What were the similar choices made by Mozart and by Caesar Rodriguez, the U.S. Air Force's last ace fighter pilot? In Mastery, Robert Greene's fifth book, he mines the biographies of great historical figures for clues about gaining control over our own lives and destinies. Picking up where The 48 Laws of Power left off, Greene culls years of research and original interviews to blend historical anecdote and psychological insight, distilling the universal ingredients of the world's masters.", 
            rating: 4.5,
            price: 7.99,
            image: "https://m.media-amazon.com/images/I/41y9IkSGfwL.jpg",
            total_quantity: 250,
            quantity_in_stock: 64,
            date_added: DateTime.new(2022, 1, 27, 12, 23, 54),
            discount: 10)

Book.create(title: "Letters to the Sons of Society: A Father's Invitation to Love, Honesty, and Freedom", 
            author: "Shaka Senghor", 
            genre: "Philosophy", 
            category: "Nonfiction", 
            description: "Shaka Senghor has lived the life of two fathers. With his first son, Jay, born shortly after Senghor was incarcerated for second-degree murder, he experienced the regret of his own mistakes and the disconnection caused by a society that sees Black lives as disposable. With his second, Sekou, born after Senghor's release, he has experienced healing, transformation, intimacy, and the possibilities of a world where men and boys can openly show one another affection, support, and love.", 
            rating: 4.70,
            price: 13.99,
            image: "https://m.media-amazon.com/images/I/51tVbKlqMqL.jpg",
            total_quantity: 483,
            quantity_in_stock: 226,
            date_added: DateTime.new(2022, 1, 27, 11, 47, 27),
            discount: 0)

Book.create(title: "48 laws of Power", 
            author: "Robert Greene", 
            genre: "Philosophy", 
            category: "Nonfiction", 
            description: "Amoral, cunning, ruthless, and instructive, this piercing work distills 3,000 years of the history of power into 48 well-explicated laws. This bold volume outlines the laws of power in their unvarnished essence, synthesizing the philosophies of Machiavelli, Sun Tzu, Carl von Clausewitz, and other infamous strategists. The 48 Laws of Power will fascinate any listener interested in gaining, observing, or defending against ultimate control.", 
            rating: 4,
            price: 16.99,
            image: "https://m.media-amazon.com/images/I/41dTDMW9IhL.jpg",
            total_quantity: 150,
            quantity_in_stock: 57,
            date_added: DateTime.new(2022, 1, 27, 12, 11, 18),
            discount: 48)

Book.create(title: "How to win friends and influence people", 
            author: "Dale Carnegie", 
            genre: "Philosophy", 
            category: "Nonfiction", 
            description: "In a great green room, tucked away in bed, is a little bunny. 'Goodnight room, goodnight moon.' And to all the familiar things in the softly lit room -- to the picture of the three little bears sitting on chairs, to the clocks and his socks, to the mittens and the kittens, to everything one by one -- the little bunny says goodnight.\n\nIn this classic of children's literature, beloved by generations of readers and listeners, the quiet poetry of the words and the gentle, lulling illustrations combine to make a perfect book for the end of the day.", 
            rating: 4.8,
            price: 10.13,
            image: "https://m.media-amazon.com/images/I/41LCdcem0hL._SY346_.jpg",
            total_quantity: 430,
            quantity_in_stock: 165,
            date_added: DateTime.new(2022, 1, 27, 12, 23, 40),
            discount: 10)

Book.create(title: "Yogi: A Life Behind the Mask", 
            author: "Jon Pessah", 
            genre: "Biography", 
            category: "Nonfiction", 
            description: "Discover the definitive biography of Yogi Berra, the New York Yankees icon, winner of 10 World Series championships, and the most-quoted player in baseball history.", 
            rating: 4.29,
            price: 10.13,
            image: "https://images-na.ssl-images-amazon.com/images/I/51Xi5EqIzLL._SX327_BO1,204,203,200_.jpg",
            total_quantity: 200,
            quantity_in_stock: 89,
            date_added: DateTime.new(2022, 1, 27, 1, 2, 45),
            discount:0)

Book.create(title: "Lou Gehrig: The Lost Memoir", 
            author: "Alan D. Gaff", 
            genre: "Biography", 
            category: "Nonfiction", 
            description: "At the tender age of twenty-four, Lou Gehrig decided to tell the remarkable story of his life and career. He was one of the most famous athletes in the country, in the midst of a record-breaking season with the legendary 1927 World Series-winning Yankees. In an effort to grow Lou’s star, pioneering sports agent Christy Walsh arranged for Lou’s tale of baseball greatness to syndicate in newspapers across the country. Until now, those columns were largely forgotten and lost to history.\n\nLou comes alive in this inspiring memoir. It is a heartfelt rags-to-riches tale about a dirt poor kid from New York who became one of the most revered baseball players of all time.\n\nFourteen years after his account, Lou would tragically die from ALS, a neuromuscular disorder now known as Lou Gehrig’s Disease. His poignant autobiography is followed by an insightful biographical essay by historian Alan D. Gaff. Here is Lou—Hall of Famer, All Star, and MVP—back at bat.", 
            rating: 4.38,
            price: 12.99,
            image: "https://m.media-amazon.com/images/P/1982132396.01._SCLZZZZZZZ_SX500_.jpg",
            total_quantity: 345,
            quantity_in_stock: 234,
            date_added: DateTime.new(2022, 1, 27, 1, 15, 55),
            discount: 0)

Book.create(title: "Life with Picasso", 
            author: "Françoise Gilot", 
            genre: "Biography", 
            category: "Nonfiction", 
            description: "Françoise Gilot's candid memoir remains the most revealing portrait of Picasso written, and gives fascinating insight into the intense and creative life shared by two modern artists.\n\nFrançoise Gilot was in her early twenties when she met the sixty-one-year-old Pablo Picasso in 1943. Brought up in a well-to-do upper-middle-class family, who had sent her to Cambridge and the Sorbonne and hoped that she would go into law, the young woman defied their wishes and set her sights on being an artist. Her introduction to Picasso led to a friendship, a love affair, and a relationship of ten years, during which Gilot gave birth to Picasso’s two children, Paloma and Claude. Gilot was one of Picasso’s muses; she was also very much her own woman, determined to make herself into the remarkable painter she did indeed become.", 
            rating: 3.75, 
            price: 11.99,
            image: "https://images-na.ssl-images-amazon.com/images/I/71ssuk3Q4vL.jpg",
            total_quantity: 324,
            quantity_in_stock: 137,
            date_added: DateTime.new(2022, 1, 27, 1, 39, 27),
            discount: 0)

Book.create(title: "Breathe: A Life in Flow", 
            author: "Rickson Gracie", 
            genre: "Biography", 
            category: "Nonfiction", 
            description: "From legendary Brazilian Jiu-Jitsu and MMA master Rickson Gracie comes a riveting, insightful memoir that weaves together the story of Gracie’s stunning career with the larger history of the Gracie family dynasty and the founding of the Ultimate Fighting Championship, showing how the connection between mind and body can be harnessed for success both inside and outside the ring.", 
            rating: 4.3,
            price: 14.99,
            image: "https://images-na.ssl-images-amazon.com/images/I/41u-JJU6W4L._SX327_BO1,204,203,200_.jpg",
            total_quantity: 350,
            quantity_in_stock: 233,
            date_added: DateTime.new(2022, 1, 27, 1, 45, 10),
            discount: 2)

Book.create(title: "Be Water, My Friend: The Teachings of Bruce Lee", 
            author: "Bruce Lee", 
            genre: "Biography", 
            category: "Nonfiction", 
            description: "Bruce Lee’s daughter illuminates her father’s most powerful life philosophies - demonstrating how martial arts are a perfect metaphor for personal growth, and how we can practice those teachings every day.\n\nEmpty your mind; be formless, shapeless like water.\n\nBruce Lee is a cultural icon, renowned the world over for his martial arts and film legacy. But Lee was also a deeply philosophical thinker, learning at an early age that martial arts are more than just an exercise in physical discipline - they are an apt metaphor for living a fully realized life.", 
            rating: 4.9,
            price: 10.99,
            image: "https://m.media-amazon.com/images/I/51qvHX1Yi3L.jpg",
            total_quantity: 437,
            quantity_in_stock: 89,
            date_added: DateTime.new(2022, 1, 27, 1, 56, 21),
            discount: 0)

Book.create(title: "Scars and Stripes", 
            author: "Tim Kennedy", 
            genre: "Biography", 
            category: "Nonfiction", 
            description: "From decorated Green Beret sniper, UFC headliner, and all around badass, Tim Kennedy, a rollicking, inspirational memoir offering lessons in how to embrace failure and weather storms, in order to unlock the strongest version of yourself.", 
            rating: 4.5,
            price: 14.99,
            image: "https://images-na.ssl-images-amazon.com/images/I/41bxhys5JhL._SX329_BO1,204,203,200_.jpg",
            total_quantity: 198,
            quantity_in_stock: 67,
            date_added: DateTime.new(2022, 1, 27, 2, 19, 33),
            discount: 25)

Book.create(title: "Lone Survivor", 
            author: "Marcus Luttrell", 
            genre: "Biography", 
            category: "Nonfiction", 
            description: "Four US Navy SEALS departed one clear night in early July 2005 for the mountainous Afghanistan-Pakistan border for a reconnaissance mission. Their task was to document the activity of an al Qaeda leader rumored to have a small army in a Taliban stronghold. Five days later, only one of those Navy SEALS made it out alive.", 
            rating: 4.6,
            price: 11.99,
            image: "https://images-na.ssl-images-amazon.com/images/I/51m+IGO9EzL._SY344_BO1,204,203,200_.jpg",
            total_quantity: 795,
            quantity_in_stock: 213,
            date_added: DateTime.new(2022, 1, 27, 2, 25, 41),
            discount: 0)

Book.create(title: "Mud, Sweat, and Tears", 
            author: "Bear Grylls", 
            genre: "Biography", 
            category: "Nonfiction", 
            description: "Already a number-one London Sunday Times best seller, Mud, Sweat, and Tears is the adrenaline-fueled autobiography of the mega-popular star of the hit survival series Man vs. Wild, adventurer Bear Grylls. A former British Special Forces commando, a man who has always sought the ultimate in dangerous challenges, Bear's true story reads like an outdoors action-and-adventure novel. But Bear's story is true - full of breathtaking escapes and remarkable exploits that would make any Jack London or H. Ryder Haggard hero proud.", 
            rating: 4.15,
            price: 11.39,
            image: "https://m.media-amazon.com/images/I/51lRPEJ6idL.jpg",
            total_quantity: 899,
            quantity_in_stock: 532,
            date_added: DateTime.new(2022, 1, 27, 2, 33, 56),
            discount: 10)

Book.create(title: "Harry Potter and the Sorcerer's Stone, Book 1", 
            author: "J.K. Rowling", 
            genre: "Fantasy", 
            category: "Fiction", 
            description: "Orphaned as an infant, young Harry Potter has been living a less-than-fortunate life. Belittled by his pompous uncle and sniveling aunt (not to mention his absolute terror of a cousin, Dudley), Harry has resigned himself to a mediocre existence in the cupboard under the stairs. But then the letters start dropping on the doormat at Number Four, Privet Drive. Addressed to “Mr. H. Potter” and stamped shut with a purple wax seal, the peculiar envelopes are swiftly confiscated by his relentlessly cruel family. But nothing stops Rubeus Hagrid, a great beetle-eyed giant of a man, from kicking down the door and bursting in with astonishing news: Harry Potter is a wizard - and not only a wizard, he’s an incredibly famous wizard. Hagrid spirits him away to Hogwarts School of Witchcraft and Wizardry, setting into motion an incredible adventure ", 
            rating: 3.8,
            price: 9.99,
            image: "https://m.media-amazon.com/images/I/91tDBrO2u9L._AC_UY218_.jpg",
            total_quantity: 750,
            quantity_in_stock: 448,
            date_added: DateTime.new(2022, 1, 27, 2, 45, 23),
            discount: 15)

Book.create(title: "Harry Potter and the Chamber of Secrets, Book 2", 
            author: "J.K. Rowling", 
            genre: "Fantasy", 
            category: "Fiction", 
            description: "There is a plot, Harry Potter. A plot to make most terrible things happen at Hogwarts School of Witchcraft and Wizardry this year.\n\nHarry Potter's summer has included the worst birthday ever, doomy warnings from a house-elf called Dobby, and rescue from the Dursleys by his friend Ron Weasley in a magical flying car! Back at Hogwarts School of Witchcraft and Wizardry for his second year, Harry hears strange whispers echo through empty corridors - and then the attacks start. Students are found as though turned to stone.... Dobby's sinister predictions seem to be coming true.", 
            rating: 4.6,
            price: 9.99,
            image: "https://m.media-amazon.com/images/I/51RDEwuovQL.jpg",
            total_quantity: 750,
            quantity_in_stock: 567,
            date_added: DateTime.new(2022, 1, 27, 2, 58, 34),
            discount: 15)

Book.create(title: "Harry Potter and the Prisoner of Azkaban, Book 3", 
            author: "J.K. Rowling", 
            genre: "Fantasy", 
            category: "Fiction", 
            description: "Welcome to the Knight Bus, emergency transport for the stranded witch or wizard. Just stick out your wand hand, step on board and we can take you anywhere you want to go.\n\nWhen the Knight Bus crashes through the darkness and screeches to a halt in front of him, it's the start of another far-from-ordinary year at Hogwarts for Harry Potter. Sirius Black, escaped mass-murderer and follower of Lord Voldemort, is on the run - and they say he is coming after Harry. In his first ever Divination class, Professor Trelawney sees an omen of death in Harry's tea leaves.... But perhaps most terrifying of all are the Dementors patrolling the school grounds, with their soul-sucking kiss....", 
            rating: 4.4,
            price: 9.99,
            image: "https://m.media-amazon.com/images/I/511LCj4HF2L.jpg",
            total_quantity: 750,
            quantity_in_stock: 586,
            date_added: DateTime.new(2022, 1, 27, 3, 11, 40),
            discount: 15)

Book.create(title: "Harry Potter and the Goblet of Fire, Book 4", 
            author: "J.K. Rowling", 
            genre: "Fantasy", 
            category: "Fiction", 
            description: "There will be three tasks, spaced throughout the school year, and they will test the champions in many different ways...their magical prowess - their daring - their powers of deduction - and, of course, their ability to cope with danger.\n\nThe Triwizard Tournament is to be held at Hogwarts. Only wizards who are over seventeen are allowed to enter - but that doesn't stop Harry dreaming that he will win the competition. Then at Hallowe'en, when the Goblet of Fire makes its selection, Harry is amazed to find his name is one of those that the magical cup picks out. He will face death-defying tasks, dragons, and dark wizards, but with the help of his best friends, Ron and Hermione, he might just make it through - alive!", 
            rating: 3.9,
            price: 9.99,
            image: "https://m.media-amazon.com/images/I/51g0LdfhtvL.jpg",
            total_quantity: 750,
            quantity_in_stock: 673,
            date_added: DateTime.new(2022, 1, 27, 3, 20, 38),
            discount: 15)

Book.create(title: "Harry Potter and the Order of the Phoenix, Book 5 ", 
            author: "J.K. Rowling", 
            genre: "Fantasy", 
            category: "Fiction", 
            description: "You are sharing the Dark Lord's thoughts and emotions. The Headmaster thinks it inadvisable for this to continue. He wishes me to teach you how to close your mind to the Dark Lord.\n\nDark times have come to Hogwarts. After the Dementors' attack on his cousin Dudley, Harry Potter knows that Voldemort will stop at nothing to find him. There are many who deny the Dark Lord's return, but Harry is not alone: a secret order gathers at Grimmauld Place to fight against the dark forces. Harry must allow Professor Snape to teach him how to protect himself from Voldemort's savage assaults on his mind. But they are growing stronger by the day and Harry is running out of time....", 
            rating: 3,
            price: 9.99,
            image: "https://m.media-amazon.com/images/I/51ok3DFBrRL.jpg",
            total_quantity: 750,
            quantity_in_stock: 457,
            date_added: DateTime.new(2022, 1, 27, 3, 22, 58),
            discount: 15)

Book.create(title: "Harry Potter and the Half-Blood Prince, Book 6", 
            author: "J.K. Rowling", 
            genre: "Fantasy", 
            category: "Fiction", 
            description: "There it was, hanging in the sky above the school: the blazing green skull with a serpent tongue, the mark Death Eaters left behind whenever they had entered a building...wherever they had murdered....\n\nWhen Dumbledore arrives at Privet Drive one summer night to collect Harry Potter, his wand hand is blackened and shrivelled, but he does not reveal why. Secrets and suspicion are spreading through the wizarding world, and Hogwarts itself is not safe. Harry is convinced that Malfoy bears the Dark Mark: there is a Death Eater amongst them. Harry will need powerful magic and true friends as he explores Voldemort's darkest secrets, and Dumbledore prepares him to face his destiny....", 
            rating: 4.6,
            price: 9.99,
            image: "https://m.media-amazon.com/images/I/51P19GScNwL.jpg",
            total_quantity: 750,
            quantity_in_stock: 315,
            date_added: DateTime.new(2022, 1, 27, 3, 28, 53),
            discount: 15)

Book.create(title: "Harry Potter and the Deathly Hallows, Book 7", 
            author: "J.K. Rowling", 
            genre: "Fantasy", 
            category: "Fiction", 
            description: "Give me Harry Potter', said Voldemort's voice, 'and none shall be harmed. Give me Harry Potter, and I shall leave the school untouched. Give me Harry Potter, and you will be rewarded.\n\nAs he climbs into the sidecar of Hagrid's motorbike and takes to the skies, leaving Privet Drive for the last time, Harry Potter knows that Lord Voldemort and the Death Eaters are not far behind. The protective charm that has kept Harry safe until now is broken, but he cannot keep hiding. The Dark Lord is breathing fear into everything Harry loves and to stop him Harry will have to find and destroy the remaining Horcruxes. The final battle must begin - Harry must stand and face his enemy....", 
            rating: 4.2,
            price: 9.99,
            image: "https://m.media-amazon.com/images/I/51g7fkELjaL.jpg",
            total_quantity: 750,
            quantity_in_stock: 499,
            date_added: DateTime.new(2022, 1, 27, 3, 44, 8),
            discount: 15)

Book.create(title: "Hamlet", 
            author: "William Shakespeare", 
            genre: "Tragedy", 
            category: "Fiction", 
            description: "Shakespeare’s combination of violence, introspection, dark humour and rich language in Hamlet is intoxicating. It remains the world's most widely studied and performed play, and is a cornerstone of world literature.", 
            rating: 5,
            price: 11.99,
            image: "https://images-na.ssl-images-amazon.com/images/I/51xjQPZ9C5L._SX307_BO1,204,203,200_.jpg",
            total_quantity: 609,
            quantity_in_stock: 533,
            date_added: DateTime.new(2022, 1, 27, 3, 56, 42),
            discount: 0)


puts "✅  Done seeding! ✅ "
